version: "3.8"

services:
  expense-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped

  frontend:
    build:
      context: ./app
    depends_on:
      - expense-app
    ports:
      - "3000:3000"
    restart: unless-stopped


